name: "jira-find-transitions"
description: "Extract transition declarations from string"
author: "FLYWHEEL"
inputs:
  jira_base_url:
    required: true
  jira_user_email:
    required: true
  jira_api_token:
    required: true
  string:
    required: true
    description: "Provide a string to extract transition declarations from"
outputs:
  transitions:
    description: "Mapping from a Jira issue id to the associated destination id"
runs:
  using: "node12"
  main: "./dist/index.js"
